- id: jest
  name: jest
  description: "Run jest tests"
  entry: jest --no-cache
  language: node
  "types": [text]
  args: []
  require_serial: false
  verbose: true,
  pass_filenames: false
  additional_dependencies: ["jest@29.3.1"]
  minimum_pre_commit_version: "0"
